name: spor_programi_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Veya sizin Flutter sürümünüze uygun başka bir değer

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fl_chart: ^1.0.0

  # Firebase Bağımlılıkları (Buradaki girintilere DİKKAT!)
  firebase_core: ^4.0.0 # En güncel versiyonu buraya yazın
  firebase_auth: ^6.0.0 # En güncel versiyonu buraya yazın
  cloud_firestore: ^6.0.0 # En güncel versiyonu buraya yazın
  dart_openai: ^5.1.0 # Yeni eklenecek!
  url_launcher: ^6.2.1
  # firebase_core, firebase_auth, cloud_firestore aynı hizada olmalı

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true