// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbgvljZTxitEKvBHXjkhcErbTADFhAasg',
    appId: '1:142513968856:web:c80f484a5c8830ec0429ad',
    messagingSenderId: '142513968856',
    projectId: 'fitnessapp-320a7',
    authDomain: 'fitnessapp-320a7.firebaseapp.com',
    storageBucket: 'fitnessapp-320a7.firebasestorage.app',
    measurementId: 'G-6TJE02PD7Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdd6oG39hFiLuRqkEwf9PDgNlDt_KP2B8',
    appId: '1:142513968856:android:ee2a28ae108dfc660429ad',
    messagingSenderId: '142513968856',
    projectId: 'fitnessapp-320a7',
    storageBucket: 'fitnessapp-320a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3gXorEvUuYH_eX4M7kTgyWEuz5Z7sYiw',
    appId: '1:142513968856:ios:02b57c70e625ea410429ad',
    messagingSenderId: '142513968856',
    projectId: 'fitnessapp-320a7',
    storageBucket: 'fitnessapp-320a7.firebasestorage.app',
    iosBundleId: 'com.example.sporProgramiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3gXorEvUuYH_eX4M7kTgyWEuz5Z7sYiw',
    appId: '1:142513968856:ios:02b57c70e625ea410429ad',
    messagingSenderId: '142513968856',
    projectId: 'fitnessapp-320a7',
    storageBucket: 'fitnessapp-320a7.firebasestorage.app',
    iosBundleId: 'com.example.sporProgramiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbgvljZTxitEKvBHXjkhcErbTADFhAasg',
    appId: '1:142513968856:web:d8e43b945690938b0429ad',
    messagingSenderId: '142513968856',
    projectId: 'fitnessapp-320a7',
    authDomain: 'fitnessapp-320a7.firebaseapp.com',
    storageBucket: 'fitnessapp-320a7.firebasestorage.app',
    measurementId: 'G-NJBW859TDN',
  );
}
